# Generated by Django 5.0.7 on 2024-07-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_cotizacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=200)),
                ('tiempo_entrega', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=100)),
                ('foto_empleado', models.ImageField(blank=True, null=True, upload_to='fotos_empleados/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compras',
                'ordering': ['-created_at'],
            },
        ),
    ]
