# Generated by Django 5.0.7 on 2024-07-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='foto_empleado',
            new_name='foto_producto',
        ),
    ]
